version: '1.1'
services:
  prod:
    build:
      context: .
      dockerfile: dockerfile

    environment:
      FRONTEND_URL: http://172.31.13.55:3000/
      BACKEND_URL: http://172.31.13.55:3001/
      DOMAIN: getinjurysync.com
    restart: always
    volumes:
      - /home/ubuntu/injury-sync/docker-nginx/ssl/.well-known:/usr/share/nginx/html/.well-known
      - /home/ubuntu/injury-sync/docker-nginx/ssl/certificate.crt:/etc/ssl/certs/certificate.crt
      - /home/ubuntu/injury-sync/docker-nginx/ssl/private.key:/etc/ssl/private/private.key
      - /home/ubuntu/injury-sync/docker-nginx/ssl/ca_bundle.crt:/etc/ssl/certs/ca_bundle.crt


    ports:
      - 80:80
      - 443:443
    container_name: nginx-container
  # qa:
  #   build:
  #     context: .
  #     dockerfile: dockerfile
  #   environment:
  #     BACKEND_URL: http://host.docker.internal:8080/
  #   volumes:
  #     - ./dist:/usr/share/nginx/html
  #   ports:
  #     - 80:80


  #   container_name: nginx-qa-container
